# Generated by Django 3.1.2 on 2023-06-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=60, null=True, verbose_name='Отчёство')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('organization', models.CharField(max_length=120, null=True, verbose_name='Организация')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Телефон')),
                ('text', models.TextField(verbose_name='Текст обращения')),
                ('file', models.FileField(null=True, upload_to='files/', verbose_name='Прикрепить файл')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
    ]
